### ISSUE TITLE
Remove JAVA_OPTS logging from hz -V output

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-packaging#144]
Here's the current output of `hz -V` (using latest `5.2-SNAPSHOT`, commit `d084672`):
```
[jholusa@jiricomp ~]$ hz -V
########################################
# JAVA=/usr/bin/java
# JAVA_OPTS=--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.logging.type=log4j2 -Dlog4j.configurationFile=file:/usr/lib/hazelcast/config/log4j2.properties -Dhazelcast.config=/usr/lib/hazelcast/config/hazelcast.xml -Djet.custom.lib.dir=/usr/lib/hazelcast/custom-lib
# CLASSPATH=:/usr/lib/hazelcast/lib:/usr/lib/hazelcast/lib/*:/usr/lib/hazelcast/bin/user-lib:/usr/lib/hazelcast/bin/user-lib/*
########################################
WARNING: package com.ibm.lang.management.internal not in jdk.management
Version: 5.2-SNAPSHOT
```

As a user, I expect this:
```
[jholusa@jiricomp ~]$ hz -V
Version: 5.2-SNAPSHOT
```

As discussed in https://hazelcast.slack.com/archives/C02JGKJD9NY/p1650441929069059?thread_ts=1650439739.820989&cid=C02JGKJD9NY , we're not talking about removing the `JAVA_OPTS` printing entirely when starting the member, but only from the `hz -V` output.

The other warning `WARNING: package com.ibm.lang.management.internal not in jdk.management` is a separate issue https://github.com/hazelcast/hazelcast/issues/20908

**Comment by obedsoto** [comment]
How can collaborate with this issue?
Thank you.

**Comment by ldziedziul** [comment]
Hi @obedsoto, thanks for your help :) 

Actually, the fix should be applied here: https://github.com/hazelcast/hazelcast/blob/4bd78004dd5c5289475b63fab6a868b237adb94f/distribution/src/bin-filemode-755/hz#L102-L106

So whenever we detect that `hz` was called with `-V` only we should skip echoing the JAVA/JAVA_OPTS/CLASSPATH details.

Should I assign this issue to you?

**Comment by obedsoto** [comment]
> Hi @obedsoto, thanks for your help :)
> 
> Actually, the fix should be applied here: https://github.com/hazelcast/hazelcast/blob/4bd78004dd5c5289475b63fab6a868b237adb94f/distribution/src/bin-filemode-755/hz#L102-L106
> 
> So whenever we detect that `hz` was called with `-V` only we should skip echoing the JAVA/JAVA_OPTS/CLASSPATH details.
> 
> Should I assign this issue to you?

Yes please!

Thank you

**Comment by obedsoto** [comment]
@ldziedziul I created a PR for this issue, can you assign me https://github.com/hazelcast/hazelcast/issues/20908?

Thank you.
