### ISSUE TITLE
Add Windows environment support

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-packaging#17]
Currently, the tool only works on UNIX based operating systems. Win support should be added.

**Comment by nfrankel** [comment]
Perhaps using GraalVM native binary tool, we could support more OS, as well as avoiding Java dependencies?

**Comment by ldziedziul** [comment]
Closing old issues, not relevant anymore, this repo contains only tools for packaging, see https://github.com/hazelcast/hazelcast-commandline-client
