### ISSUE TITLE
Hazelcast RPM repository fails to sync with Redhat Satellite due to missing filelist in repomod.xml

### ISSUE THREAD

**Issue by ebreen** [hazelcast/hazelcast-packaging#182]
Hi,

We are not able to sync the provided repository in Satellite. Satellite throws the following error: XML file(s): filelists not found
This seems to be an issue others have experienced with jFrog repos as well: https://community.theforeman.org/t/external-private-yum-repository-on-jfrog-io-not-synchronizing-in-foreman-katello/24938
The issue seems to be that the repomod.xml does not contain a filelist.

https://repository.hazelcast.com/rpm/stable/

**Comment by Siilveer** [comment]
The isue is not resolved. Satellite still reports the same error, when trying to sync  "https://repository.hazelcast.com/rpm/stable/"


XML file(s): filelists not found

**Comment by ldziedziul** [comment]
Could you retry now?
