### ISSUE TITLE
Problem with upgrade Debian 12

### ISSUE THREAD

**Issue by pbakadm** [hazelcast/hazelcast-packaging#237]
Describe the bug
Installing hazelcast >=5.4.0, results:

The following packages have unmet dependencies:
hazelcast : Depends: java21-sdk-headless but it is not installable

Expected behavior
Update previosr 5.3.x version

To Reproduce
Follow: https://docs.hazelcast.com/hazelcast/5.5/getting-started/install-hazelcast

Regards :)

**Comment by pbakadm** [comment]
Hi! 
When this will be released to production? I see that merge is ready but no change for me. 

Regards

**Comment by pbakadm** [comment]
Thank you! When next release is planned? 

Regards

**Comment by JackPGreen** [comment]
> Thank you! When next release is planned?
> 
> Regards

Unfortunately I can't provide a date for that at the moment - if your an [Enterprise user](https://hazelcast.com/products/feature-comparison/) please get in contact directly for more information.
