### ISSUE TITLE
subcommand to print current config

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-packaging#81]
When creating a custom config it would be nice to easily see how does to current config look like. 
path to the config is printed when a member is starting, but it's easy to miss it. so I can imagine something like
`hz start describe` or `hz start show-config`. and obviously also `hz mc describe` 

The question is whether it should print the config or just show a path. I don't have a strong opinion here.

**Comment by Holmistr** [comment]
Or perhaps this could be printed on the help or version?

**Comment by jerrinot** [comment]
why would you ever want to conflate version and configuration? that sounds like a terrible idea.

**Comment by Holmistr** [comment]
I was mainly talking about the `help`

My reasoning - suppose that there's some `describe` command. From a user perspective that doesn't know about it - how do you discover it? You type `help` and search for the command. So you're typing help anyway and another problem is that if there are quite a few commands, it's easy to overlook it.

Therefore, we cut the step (idea proposal):
```
[jholusa@jiricomp ~]$ hz -h
Installation dir: <path>

Usage: hz [-hV] [COMMAND]
Utility for the Hazelcast operations.

Global options are:

  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  start  Starts a new Hazelcast IMDG member
  mc     Utility for Hazelcast Management Center operations.
```

BTW Maven does it with the `version` and it's probably the most useful thing I have ever seen when using with multiple Maven versions:
```
[jholusa@jiricomp ~]$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/lib/maven/apache-maven-3.6.3
Java version: 11.0.8, vendor: GraalVM Community, runtime: /usr/lib/jvm/graalvm-ce-java11-20.2.0
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "5.7.17-200.fc32.x86_64", arch: "amd64", family: "unix"
```

**Comment by Holmistr** [comment]
@ldziedziul @frant-hartm Your decision, guys.

**Comment by ldziedziul** [comment]
Closing old issues, not relevant anymore, this repo contains only tools for packaging, see https://github.com/hazelcast/hazelcast-commandline-client
