### ISSUE TITLE
Don't use Java Util Logging

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-packaging#82]
hz uses jul. It looks ugly. We switched from JUL in Docker containers. This tool should be consistent with other distributions.

**Comment by alparslanavci** [comment]
Hazelcast itself uses jul by default, here is the related issue: https://github.com/hazelcast/hazelcast/issues/16640

Agreed that it should be consistent with all distributions.

**Comment by jerrinot** [comment]
Hazelcast Maven artifacts defaults to jul. That's fine as that's the only option we can use without depending on a 3rd party library. This is for users who are building their own Hazelcast server by using the Maven artifact. 

However when we are building the distribution - Docker, tar.gz or this CLI thingie - then it's our responsibility to pick something more sensible that jul.

**Comment by alparslanavci** [comment]
Again, agreed. Currently, CLI installation is based on Hazelcast's tar.gz, which defaults to jul. Surely, we can change it for CLI, but it will mean it will be another difference from the default tar.gz distribution.

**Comment by ldziedziul** [comment]
not part of this repository anymore
